SELECT ID, IF(COLONY <= 0.25, "CRITICAL", IF(COLONY <= 0.5, "HIGH", IF(COLONY <= 0.75, "MEDIUM", "LOW"))) COLONY_NAME
FROM (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY size_of_colony DESC) COLONY
    FROM ECOLI_DATA
) A
ORDER BY ID