SELECT R.REST_ID REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) SCORE
FROM REST_REVIEW R
JOIN (
    SELECT *
    FROM REST_INFO
    WHERE ADDRESS LIKE "서울%"
) I
ON I.REST_ID = R.REST_ID
GROUP BY R.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC