SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT I.USER_ID) USERS
FROM (
    SELECT USER_ID, CAST(GENDER AS SIGNED) GENDER 
    FROM USER_INFO
    WHERE GENDER IS NOT NULL
    GROUP BY USER_ID
) I
JOIN (
    SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, USER_ID
    FROM ONLINE_SALE
) O ON I.USER_ID = O.USER_ID
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER