SELECT CONCAT(QUARTER, "Q") QUARTER, COUNT(*) ECOLI_COUNT
FROM (
    SELECT QUARTER(DIFFERENTIATION_DATE) QUARTER, ID
    FROM ECOLI_DATA
) A
JOIN ECOLI_DATA E ON A.ID = E.ID
GROUP BY QUARTER
ORDER BY QUARTER