WITH D AS (
    SELECT DURATION_TYPE DUR_TYPE, (100 - DISCOUNT_RATE) DIS
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
    UNION 
    SELECT '0일 이상' DUR_TYPE, 100 DIS
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
) 
SELECT HISTORY_ID, ROUND(DAILY_FEE * DIS / 100) * DUR FEE
FROM (
    SELECT CAR_ID, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
) C
JOIN (
    SELECT HISTORY_ID, CAR_ID, ABS(DATEDIFF(START_DATE, END_DATE)) + 1 DUR, START_DATE, END_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) H ON C.CAR_ID = H.CAR_ID
RIGHT JOIN D ON IF(DUR >= 90, DUR_TYPE = '90일 이상', IF(DUR >= 30, DUR_TYPE = '30일 이상', IF(DUR >= 7, DUR_TYPE = '7일 이상', DUR_TYPE = '0일 이상')))
ORDER BY FEE DESC, HISTORY_ID DESC