SELECT E.EMP_NO EMP_NO, EMP_NAME, GRADE, IF(GRADE = 'S', SAL * 0.2, IF(GRADE = 'A', SAL * 0.15, IF(GRADE = 'B', SAL * 0.1, 0))) BONUS
FROM HR_EMPLOYEES E
JOIN (
    SELECT EMP_NO, IF(AVG(SCORE) >= 96, 'S', IF(AVG(SCORE) >= 90, 'A', IF(AVG(SCORE) >= 80, 'B', 'C'))) GRADE 
    FROM HR_GRADE
    GROUP BY EMP_NO
) G ON E.EMP_NO = G.EMP_NO
ORDER BY E.EMP_NO