SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") REVIEW_DATE
FROM (
    SELECT COUNT(*) AS CNT_MEMBER, MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY CNT_MEMBER DESC
    LIMIT 1
) A
JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
JOIN MEMBER_PROFILE C ON A.MEMBER_ID = C.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT