SELECT TREE.ITEM_ID, ITEM_NAME, RARITY
FROM (
    SELECT ITEM_TREE.ITEM_ID AS ITEM_ID
    FROM ITEM_INFO
    INNER JOIN ITEM_TREE
    ON ITEM_INFO.ITEM_ID = ITEM_TREE.PARENT_ITEM_ID
    WHERE RARITY="RARE"
) AS TREE
INNER JOIN ITEM_INFO
ON TREE.ITEM_ID = ITEM_INFO.ITEM_ID
ORDER BY ITEM_ID DESC;