WITH A AS (    
    SELECT COUNT(*) RECORDS, CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
    GROUP BY CAR_ID
    HAVING RECORDS >= 5
)
SELECT MONTH(START_DATE) MONTH, A.CAR_ID CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
JOIN A ON A.CAR_ID = B.CAR_ID
WHERE START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
GROUP BY MONTH, CAR_ID
HAVING RECORDS != 0
ORDER BY MONTH, CAR_ID DESC;