SELECT YEAR, M_SIZE - SIZE_OF_COLONY YEAR_DEV, ID
FROM ECOLI_DATA E
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) M_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
) A ON A.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV