SELECT ID, FISH_NAME, I.LENGTH LENGTH
FROM (
    SELECT FISH_TYPE, MAX(IFNULL(LENGTH, 10)) LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) I
JOIN (
    SELECT ID, FISH_TYPE, LENGTH
    FROM FISH_INFO
) D ON I.FISH_TYPE = D.FISH_TYPE AND I.LENGTH = D.LENGTH
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
ORDER BY ID