SELECT A.CATEGORY AS CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT A
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS B_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) B
ON A.CATEGORY = B.CATEGORY AND PRICE = B_PRICE
GROUP BY CATEGORY
HAVING CATEGORY IN ("과자", "국", "김치", "식용유")
ORDER BY PRICE DESC;